/**
 * Complete bidirectional mapping between CP437 indices (0–255) and Unicode characters.
 *
 * CP437 is the original IBM PC character set. Indices 0–31 and 127 are graphical
 * glyphs (smileys, card suits, arrows, box-drawing fragments, etc.), NOT control
 * characters.
 */

interface CP437Entry {
  char: string;
  name: string;
}

const TABLE: CP437Entry[] = [
  /* 0x00 */ { char: "\u0000", name: "Null" },
  /* 0x01 */ { char: "\u263A", name: "White Smiling Face" },
  /* 0x02 */ { char: "\u263B", name: "Black Smiling Face" },
  /* 0x03 */ { char: "\u2665", name: "Black Heart Suit" },
  /* 0x04 */ { char: "\u2666", name: "Black Diamond Suit" },
  /* 0x05 */ { char: "\u2663", name: "Black Club Suit" },
  /* 0x06 */ { char: "\u2660", name: "Black Spade Suit" },
  /* 0x07 */ { char: "\u2022", name: "Bullet" },
  /* 0x08 */ { char: "\u25D8", name: "Inverse Bullet" },
  /* 0x09 */ { char: "\u25CB", name: "White Circle" },
  /* 0x0A */ { char: "\u25D9", name: "Inverse White Circle" },
  /* 0x0B */ { char: "\u2642", name: "Male Sign" },
  /* 0x0C */ { char: "\u2640", name: "Female Sign" },
  /* 0x0D */ { char: "\u266A", name: "Eighth Note" },
  /* 0x0E */ { char: "\u266B", name: "Beamed Eighth Notes" },
  /* 0x0F */ { char: "\u263C", name: "White Sun With Rays" },
  /* 0x10 */ { char: "\u25BA", name: "Black Right-Pointing Pointer" },
  /* 0x11 */ { char: "\u25C4", name: "Black Left-Pointing Pointer" },
  /* 0x12 */ { char: "\u2195", name: "Up Down Arrow" },
  /* 0x13 */ { char: "\u203C", name: "Double Exclamation Mark" },
  /* 0x14 */ { char: "\u00B6", name: "Pilcrow Sign" },
  /* 0x15 */ { char: "\u00A7", name: "Section Sign" },
  /* 0x16 */ { char: "\u25AC", name: "Black Rectangle" },
  /* 0x17 */ { char: "\u21A8", name: "Up Down Arrow With Base" },
  /* 0x18 */ { char: "\u2191", name: "Upwards Arrow" },
  /* 0x19 */ { char: "\u2193", name: "Downwards Arrow" },
  /* 0x1A */ { char: "\u2192", name: "Rightwards Arrow" },
  /* 0x1B */ { char: "\u2190", name: "Leftwards Arrow" },
  /* 0x1C */ { char: "\u221F", name: "Right Angle" },
  /* 0x1D */ { char: "\u2194", name: "Left Right Arrow" },
  /* 0x1E */ { char: "\u25B2", name: "Black Up-Pointing Triangle" },
  /* 0x1F */ { char: "\u25BC", name: "Black Down-Pointing Triangle" },
  /* 0x20 */ { char: " ", name: "Space" },
  /* 0x21 */ { char: "!", name: "Exclamation Mark" },
  /* 0x22 */ { char: '"', name: "Quotation Mark" },
  /* 0x23 */ { char: "#", name: "Number Sign" },
  /* 0x24 */ { char: "$", name: "Dollar Sign" },
  /* 0x25 */ { char: "%", name: "Percent Sign" },
  /* 0x26 */ { char: "&", name: "Ampersand" },
  /* 0x27 */ { char: "'", name: "Apostrophe" },
  /* 0x28 */ { char: "(", name: "Left Parenthesis" },
  /* 0x29 */ { char: ")", name: "Right Parenthesis" },
  /* 0x2A */ { char: "*", name: "Asterisk" },
  /* 0x2B */ { char: "+", name: "Plus Sign" },
  /* 0x2C */ { char: ",", name: "Comma" },
  /* 0x2D */ { char: "-", name: "Hyphen-Minus" },
  /* 0x2E */ { char: ".", name: "Full Stop" },
  /* 0x2F */ { char: "/", name: "Solidus" },
  /* 0x30 */ { char: "0", name: "Digit Zero" },
  /* 0x31 */ { char: "1", name: "Digit One" },
  /* 0x32 */ { char: "2", name: "Digit Two" },
  /* 0x33 */ { char: "3", name: "Digit Three" },
  /* 0x34 */ { char: "4", name: "Digit Four" },
  /* 0x35 */ { char: "5", name: "Digit Five" },
  /* 0x36 */ { char: "6", name: "Digit Six" },
  /* 0x37 */ { char: "7", name: "Digit Seven" },
  /* 0x38 */ { char: "8", name: "Digit Eight" },
  /* 0x39 */ { char: "9", name: "Digit Nine" },
  /* 0x3A */ { char: ":", name: "Colon" },
  /* 0x3B */ { char: ";", name: "Semicolon" },
  /* 0x3C */ { char: "<", name: "Less-Than Sign" },
  /* 0x3D */ { char: "=", name: "Equals Sign" },
  /* 0x3E */ { char: ">", name: "Greater-Than Sign" },
  /* 0x3F */ { char: "?", name: "Question Mark" },
  /* 0x40 */ { char: "@", name: "Commercial At" },
  /* 0x41 */ { char: "A", name: "Latin Capital Letter A" },
  /* 0x42 */ { char: "B", name: "Latin Capital Letter B" },
  /* 0x43 */ { char: "C", name: "Latin Capital Letter C" },
  /* 0x44 */ { char: "D", name: "Latin Capital Letter D" },
  /* 0x45 */ { char: "E", name: "Latin Capital Letter E" },
  /* 0x46 */ { char: "F", name: "Latin Capital Letter F" },
  /* 0x47 */ { char: "G", name: "Latin Capital Letter G" },
  /* 0x48 */ { char: "H", name: "Latin Capital Letter H" },
  /* 0x49 */ { char: "I", name: "Latin Capital Letter I" },
  /* 0x4A */ { char: "J", name: "Latin Capital Letter J" },
  /* 0x4B */ { char: "K", name: "Latin Capital Letter K" },
  /* 0x4C */ { char: "L", name: "Latin Capital Letter L" },
  /* 0x4D */ { char: "M", name: "Latin Capital Letter M" },
  /* 0x4E */ { char: "N", name: "Latin Capital Letter N" },
  /* 0x4F */ { char: "O", name: "Latin Capital Letter O" },
  /* 0x50 */ { char: "P", name: "Latin Capital Letter P" },
  /* 0x51 */ { char: "Q", name: "Latin Capital Letter Q" },
  /* 0x52 */ { char: "R", name: "Latin Capital Letter R" },
  /* 0x53 */ { char: "S", name: "Latin Capital Letter S" },
  /* 0x54 */ { char: "T", name: "Latin Capital Letter T" },
  /* 0x55 */ { char: "U", name: "Latin Capital Letter U" },
  /* 0x56 */ { char: "V", name: "Latin Capital Letter V" },
  /* 0x57 */ { char: "W", name: "Latin Capital Letter W" },
  /* 0x58 */ { char: "X", name: "Latin Capital Letter X" },
  /* 0x59 */ { char: "Y", name: "Latin Capital Letter Y" },
  /* 0x5A */ { char: "Z", name: "Latin Capital Letter Z" },
  /* 0x5B */ { char: "[", name: "Left Square Bracket" },
  /* 0x5C */ { char: "\\", name: "Reverse Solidus" },
  /* 0x5D */ { char: "]", name: "Right Square Bracket" },
  /* 0x5E */ { char: "^", name: "Circumflex Accent" },
  /* 0x5F */ { char: "_", name: "Low Line" },
  /* 0x60 */ { char: "`", name: "Grave Accent" },
  /* 0x61 */ { char: "a", name: "Latin Small Letter A" },
  /* 0x62 */ { char: "b", name: "Latin Small Letter B" },
  /* 0x63 */ { char: "c", name: "Latin Small Letter C" },
  /* 0x64 */ { char: "d", name: "Latin Small Letter D" },
  /* 0x65 */ { char: "e", name: "Latin Small Letter E" },
  /* 0x66 */ { char: "f", name: "Latin Small Letter F" },
  /* 0x67 */ { char: "g", name: "Latin Small Letter G" },
  /* 0x68 */ { char: "h", name: "Latin Small Letter H" },
  /* 0x69 */ { char: "i", name: "Latin Small Letter I" },
  /* 0x6A */ { char: "j", name: "Latin Small Letter J" },
  /* 0x6B */ { char: "k", name: "Latin Small Letter K" },
  /* 0x6C */ { char: "l", name: "Latin Small Letter L" },
  /* 0x6D */ { char: "m", name: "Latin Small Letter M" },
  /* 0x6E */ { char: "n", name: "Latin Small Letter N" },
  /* 0x6F */ { char: "o", name: "Latin Small Letter O" },
  /* 0x70 */ { char: "p", name: "Latin Small Letter P" },
  /* 0x71 */ { char: "q", name: "Latin Small Letter Q" },
  /* 0x72 */ { char: "r", name: "Latin Small Letter R" },
  /* 0x73 */ { char: "s", name: "Latin Small Letter S" },
  /* 0x74 */ { char: "t", name: "Latin Small Letter T" },
  /* 0x75 */ { char: "u", name: "Latin Small Letter U" },
  /* 0x76 */ { char: "v", name: "Latin Small Letter V" },
  /* 0x77 */ { char: "w", name: "Latin Small Letter W" },
  /* 0x78 */ { char: "x", name: "Latin Small Letter X" },
  /* 0x79 */ { char: "y", name: "Latin Small Letter Y" },
  /* 0x7A */ { char: "z", name: "Latin Small Letter Z" },
  /* 0x7B */ { char: "{", name: "Left Curly Bracket" },
  /* 0x7C */ { char: "|", name: "Vertical Line" },
  /* 0x7D */ { char: "}", name: "Right Curly Bracket" },
  /* 0x7E */ { char: "~", name: "Tilde" },
  /* 0x7F */ { char: "\u2302", name: "House" },
  /* 0x80 */ { char: "\u00C7", name: "Latin Capital Letter C With Cedilla" },
  /* 0x81 */ { char: "\u00FC", name: "Latin Small Letter U With Diaeresis" },
  /* 0x82 */ { char: "\u00E9", name: "Latin Small Letter E With Acute" },
  /* 0x83 */ { char: "\u00E2", name: "Latin Small Letter A With Circumflex" },
  /* 0x84 */ { char: "\u00E4", name: "Latin Small Letter A With Diaeresis" },
  /* 0x85 */ { char: "\u00E0", name: "Latin Small Letter A With Grave" },
  /* 0x86 */ { char: "\u00E5", name: "Latin Small Letter A With Ring Above" },
  /* 0x87 */ { char: "\u00E7", name: "Latin Small Letter C With Cedilla" },
  /* 0x88 */ { char: "\u00EA", name: "Latin Small Letter E With Circumflex" },
  /* 0x89 */ { char: "\u00EB", name: "Latin Small Letter E With Diaeresis" },
  /* 0x8A */ { char: "\u00E8", name: "Latin Small Letter E With Grave" },
  /* 0x8B */ { char: "\u00EF", name: "Latin Small Letter I With Diaeresis" },
  /* 0x8C */ { char: "\u00EE", name: "Latin Small Letter I With Circumflex" },
  /* 0x8D */ { char: "\u00EC", name: "Latin Small Letter I With Grave" },
  /* 0x8E */ { char: "\u00C4", name: "Latin Capital Letter A With Diaeresis" },
  /* 0x8F */ { char: "\u00C5", name: "Latin Capital Letter A With Ring Above" },
  /* 0x90 */ { char: "\u00C9", name: "Latin Capital Letter E With Acute" },
  /* 0x91 */ { char: "\u00E6", name: "Latin Small Letter Ae" },
  /* 0x92 */ { char: "\u00C6", name: "Latin Capital Letter Ae" },
  /* 0x93 */ { char: "\u00F4", name: "Latin Small Letter O With Circumflex" },
  /* 0x94 */ { char: "\u00F6", name: "Latin Small Letter O With Diaeresis" },
  /* 0x95 */ { char: "\u00F2", name: "Latin Small Letter O With Grave" },
  /* 0x96 */ { char: "\u00FB", name: "Latin Small Letter U With Circumflex" },
  /* 0x97 */ { char: "\u00F9", name: "Latin Small Letter U With Grave" },
  /* 0x98 */ { char: "\u00FF", name: "Latin Small Letter Y With Diaeresis" },
  /* 0x99 */ { char: "\u00D6", name: "Latin Capital Letter O With Diaeresis" },
  /* 0x9A */ { char: "\u00DC", name: "Latin Capital Letter U With Diaeresis" },
  /* 0x9B */ { char: "\u00A2", name: "Cent Sign" },
  /* 0x9C */ { char: "\u00A3", name: "Pound Sign" },
  /* 0x9D */ { char: "\u00A5", name: "Yen Sign" },
  /* 0x9E */ { char: "\u20A7", name: "Peseta Sign" },
  /* 0x9F */ { char: "\u0192", name: "Latin Small Letter F With Hook" },
  /* 0xA0 */ { char: "\u00E1", name: "Latin Small Letter A With Acute" },
  /* 0xA1 */ { char: "\u00ED", name: "Latin Small Letter I With Acute" },
  /* 0xA2 */ { char: "\u00F3", name: "Latin Small Letter O With Acute" },
  /* 0xA3 */ { char: "\u00FA", name: "Latin Small Letter U With Acute" },
  /* 0xA4 */ { char: "\u00F1", name: "Latin Small Letter N With Tilde" },
  /* 0xA5 */ { char: "\u00D1", name: "Latin Capital Letter N With Tilde" },
  /* 0xA6 */ { char: "\u00AA", name: "Feminine Ordinal Indicator" },
  /* 0xA7 */ { char: "\u00BA", name: "Masculine Ordinal Indicator" },
  /* 0xA8 */ { char: "\u00BF", name: "Inverted Question Mark" },
  /* 0xA9 */ { char: "\u2310", name: "Reversed Not Sign" },
  /* 0xAA */ { char: "\u00AC", name: "Not Sign" },
  /* 0xAB */ { char: "\u00BD", name: "Vulgar Fraction One Half" },
  /* 0xAC */ { char: "\u00BC", name: "Vulgar Fraction One Quarter" },
  /* 0xAD */ { char: "\u00A1", name: "Inverted Exclamation Mark" },
  /* 0xAE */ { char: "\u00AB", name: "Left-Pointing Double Angle Quotation Mark" },
  /* 0xAF */ { char: "\u00BB", name: "Right-Pointing Double Angle Quotation Mark" },
  /* 0xB0 */ { char: "\u2591", name: "Light Shade" },
  /* 0xB1 */ { char: "\u2592", name: "Medium Shade" },
  /* 0xB2 */ { char: "\u2593", name: "Dark Shade" },
  /* 0xB3 */ { char: "\u2502", name: "Box Drawings Light Vertical" },
  /* 0xB4 */ { char: "\u2524", name: "Box Drawings Light Vertical And Left" },
  /* 0xB5 */ { char: "\u2561", name: "Box Drawings Vertical Single And Left Double" },
  /* 0xB6 */ { char: "\u2562", name: "Box Drawings Vertical Double And Left Single" },
  /* 0xB7 */ { char: "\u2556", name: "Box Drawings Down Double And Left Single" },
  /* 0xB8 */ { char: "\u2555", name: "Box Drawings Down Single And Left Double" },
  /* 0xB9 */ { char: "\u2563", name: "Box Drawings Double Vertical And Left" },
  /* 0xBA */ { char: "\u2551", name: "Box Drawings Double Vertical" },
  /* 0xBB */ { char: "\u2557", name: "Box Drawings Double Down And Left" },
  /* 0xBC */ { char: "\u255D", name: "Box Drawings Double Up And Left" },
  /* 0xBD */ { char: "\u255C", name: "Box Drawings Up Double And Left Single" },
  /* 0xBE */ { char: "\u255B", name: "Box Drawings Up Single And Left Double" },
  /* 0xBF */ { char: "\u2510", name: "Box Drawings Light Down And Left" },
  /* 0xC0 */ { char: "\u2514", name: "Box Drawings Light Up And Right" },
  /* 0xC1 */ { char: "\u2534", name: "Box Drawings Light Up And Horizontal" },
  /* 0xC2 */ { char: "\u252C", name: "Box Drawings Light Down And Horizontal" },
  /* 0xC3 */ { char: "\u251C", name: "Box Drawings Light Vertical And Right" },
  /* 0xC4 */ { char: "\u2500", name: "Box Drawings Light Horizontal" },
  /* 0xC5 */ { char: "\u253C", name: "Box Drawings Light Vertical And Horizontal" },
  /* 0xC6 */ { char: "\u255E", name: "Box Drawings Vertical Single And Right Double" },
  /* 0xC7 */ { char: "\u255F", name: "Box Drawings Vertical Double And Right Single" },
  /* 0xC8 */ { char: "\u255A", name: "Box Drawings Double Up And Right" },
  /* 0xC9 */ { char: "\u2554", name: "Box Drawings Double Down And Right" },
  /* 0xCA */ { char: "\u2569", name: "Box Drawings Double Up And Horizontal" },
  /* 0xCB */ { char: "\u2566", name: "Box Drawings Double Down And Horizontal" },
  /* 0xCC */ { char: "\u2560", name: "Box Drawings Double Vertical And Right" },
  /* 0xCD */ { char: "\u2550", name: "Box Drawings Double Horizontal" },
  /* 0xCE */ { char: "\u256C", name: "Box Drawings Double Vertical And Horizontal" },
  /* 0xCF */ { char: "\u2567", name: "Box Drawings Up Single And Horizontal Double" },
  /* 0xD0 */ { char: "\u2568", name: "Box Drawings Up Double And Horizontal Single" },
  /* 0xD1 */ { char: "\u2564", name: "Box Drawings Down Single And Horizontal Double" },
  /* 0xD2 */ { char: "\u2565", name: "Box Drawings Down Double And Horizontal Single" },
  /* 0xD3 */ { char: "\u2559", name: "Box Drawings Up Double And Right Single" },
  /* 0xD4 */ { char: "\u2558", name: "Box Drawings Up Single And Right Double" },
  /* 0xD5 */ { char: "\u2552", name: "Box Drawings Down Single And Right Double" },
  /* 0xD6 */ { char: "\u2553", name: "Box Drawings Down Double And Right Single" },
  /* 0xD7 */ { char: "\u256B", name: "Box Drawings Vertical Double And Horizontal Single" },
  /* 0xD8 */ { char: "\u256A", name: "Box Drawings Vertical Single And Horizontal Double" },
  /* 0xD9 */ { char: "\u2518", name: "Box Drawings Light Up And Left" },
  /* 0xDA */ { char: "\u250C", name: "Box Drawings Light Down And Right" },
  /* 0xDB */ { char: "\u2588", name: "Full Block" },
  /* 0xDC */ { char: "\u2584", name: "Lower Half Block" },
  /* 0xDD */ { char: "\u258C", name: "Left Half Block" },
  /* 0xDE */ { char: "\u2590", name: "Right Half Block" },
  /* 0xDF */ { char: "\u2580", name: "Upper Half Block" },
  /* 0xE0 */ { char: "\u03B1", name: "Greek Small Letter Alpha" },
  /* 0xE1 */ { char: "\u00DF", name: "Latin Small Letter Sharp S" },
  /* 0xE2 */ { char: "\u0393", name: "Greek Capital Letter Gamma" },
  /* 0xE3 */ { char: "\u03C0", name: "Greek Small Letter Pi" },
  /* 0xE4 */ { char: "\u03A3", name: "Greek Capital Letter Sigma" },
  /* 0xE5 */ { char: "\u03C3", name: "Greek Small Letter Sigma" },
  /* 0xE6 */ { char: "\u00B5", name: "Micro Sign" },
  /* 0xE7 */ { char: "\u03C4", name: "Greek Small Letter Tau" },
  /* 0xE8 */ { char: "\u03A6", name: "Greek Capital Letter Phi" },
  /* 0xE9 */ { char: "\u0398", name: "Greek Capital Letter Theta" },
  /* 0xEA */ { char: "\u03A9", name: "Greek Capital Letter Omega" },
  /* 0xEB */ { char: "\u03B4", name: "Greek Small Letter Delta" },
  /* 0xEC */ { char: "\u221E", name: "Infinity" },
  /* 0xED */ { char: "\u03C6", name: "Greek Small Letter Phi" },
  /* 0xEE */ { char: "\u03B5", name: "Greek Small Letter Epsilon" },
  /* 0xEF */ { char: "\u2229", name: "Intersection" },
  /* 0xF0 */ { char: "\u2261", name: "Identical To" },
  /* 0xF1 */ { char: "\u00B1", name: "Plus-Minus Sign" },
  /* 0xF2 */ { char: "\u2265", name: "Greater-Than Or Equal To" },
  /* 0xF3 */ { char: "\u2264", name: "Less-Than Or Equal To" },
  /* 0xF4 */ { char: "\u2320", name: "Top Half Integral" },
  /* 0xF5 */ { char: "\u2321", name: "Bottom Half Integral" },
  /* 0xF6 */ { char: "\u00F7", name: "Division Sign" },
  /* 0xF7 */ { char: "\u2248", name: "Almost Equal To" },
  /* 0xF8 */ { char: "\u00B0", name: "Degree Sign" },
  /* 0xF9 */ { char: "\u2219", name: "Bullet Operator" },
  /* 0xFA */ { char: "\u00B7", name: "Middle Dot" },
  /* 0xFB */ { char: "\u221A", name: "Square Root" },
  /* 0xFC */ { char: "\u207F", name: "Superscript Latin Small Letter N" },
  /* 0xFD */ { char: "\u00B2", name: "Superscript Two" },
  /* 0xFE */ { char: "\u25A0", name: "Black Square" },
  /* 0xFF */ { char: "\u00A0", name: "No-Break Space" },
];

/** Reverse lookup: Unicode character -> CP437 index. */
const UNICODE_TO_CP437 = new Map<string, number>();
for (let i = 0; i < TABLE.length; i++) {
  UNICODE_TO_CP437.set(TABLE[i].char, i);
}

/**
 * Returns the Unicode character for a CP437 index (0–255).
 * Throws a RangeError if the index is out of bounds.
 */
export function cp437ToUnicode(index: number): string {
  if (index < 0 || index > 255) {
    throw new RangeError(`CP437 index out of range: ${index}`);
  }
  return TABLE[index].char;
}

/**
 * Returns the CP437 index (0–255) for a Unicode character,
 * or `undefined` if the character has no CP437 representation.
 */
export function unicodeToCP437(char: string): number | undefined {
  return UNICODE_TO_CP437.get(char);
}

/**
 * Returns a human-readable name for the glyph at the given CP437 index.
 * Throws a RangeError if the index is out of bounds.
 */
export function cp437Name(index: number): string {
  if (index < 0 || index > 255) {
    throw new RangeError(`CP437 index out of range: ${index}`);
  }
  return TABLE[index].name;
}
